---
version: 2

project_name: e-shop-fiber-microservice-boilerplate

builds:
  - id: binary-build
    main: ./cmd/main.go
    binary: ./dist/app
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

dockers:
  - goos: linux
    goarch: amd64
    use: buildx
    ids:
      - binary-build
    image_templates:
      - "WildEgor/e-shop-fiber-microservice-boilerplate:latest-amd64"
      - "WildEgor/e-shop-fiber-microservice-boilerplate:{{.Tag}}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
    dockerfile: Dockerfile
    extra_files:
      - assets

  - goos: linux
    goarch: arm64
    use: buildx
    ids:
      - binary-build
    image_templates:
      - "WildEgor/e-shop-fiber-microservice-boilerplate:latest-arm64v8"
      - "WildEgor/e-shop-fiber-microservice-boilerplate:{{.Tag}}-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    dockerfile: Dockerfile
    extra_files:
      - assets

docker_manifests:
  - name_template: vgarvardt/rklotz:latest
    image_templates:
      - "WildEgor/e-shop-fiber-microservice-boilerplate:latest-amd64"
      - "WildEgor/e-shop-fiber-microservice-boilerplate:latest-arm64v8"
  - name_template: WildEgor/e-shop-fiber-microservice-boilerplate:{{.Tag}}
    image_templates:
      - "WildEgor/e-shop-fiber-microservice-boilerplate:{{.Tag}}-amd64"
      - "WildEgor/e-shop-fiber-microservice-boilerplate:{{.Tag}}-arm64v8"
