version: '3'

tasks:
  # Run using docker
  docker:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f docker-compose.yml
    cmd: docker-compose up -d app-docker

  # Run locally with hot-reload
  local:
    cmd: air -d

  # Update DI deps
  wire:
    cmd: cd internal && wire

  # Update swagger files
  swag:
    cmd: swag init -g cmd/main.go --output api/swagger