// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package pkg

import (
	"github.com/WildEgor/e-shop-fiber-microservice-boilerplate/internal/config"
	"github.com/WildEgor/e-shop-fiber-microservice-boilerplate/internal/handlers/errors"
	"github.com/WildEgor/e-shop-fiber-microservice-boilerplate/internal/handlers/health_check"
	"github.com/WildEgor/e-shop-fiber-microservice-boilerplate/internal/handlers/ready_check"
	"github.com/WildEgor/e-shop-fiber-microservice-boilerplate/internal/router"
	"github.com/google/wire"
)

// Injectors from server.go:

func NewServer() (*Server, error) {
	configurator := config.NewConfigurator()
	appConfig := config.NewAppConfig(configurator)
	errorsHandler := error_handler.NewErrorsHandler()
	privateRouter := router.NewPrivateRouter()
	healthCheckHandler := health_check_handler.NewHealthCheckHandler()
	readyCheckHandler := ready_check_handler.NewReadyCheckHandler()
	publicRouter := router.NewPublicRouter(healthCheckHandler, readyCheckHandler)
	swaggerRouter := router.NewSwaggerRouter()
	server := NewApp(appConfig, errorsHandler, privateRouter, publicRouter, swaggerRouter)
	return server, nil
}

// server.go:

var ServerSet = wire.NewSet(AppSet)
