---
name: "Lint"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name != 'pull_request' }}
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: '.*(assets/.*|\.goreleaser\.yml|api/.*\.(yml|json)|README\.md|test/request/.*)'
          # go validator works pretty bad in super-linter, we'll use the original one
          VALIDATE_GO: false
          # do not validate SQL - linters are pretty useless in case of this library,
          # and the functionality is tested using integration tests
          VALIDATE_SQL: false
          VALIDATE_SQLFLUFF: false
          VALIDATE_CHECKOV: false
          VALIDATE_YAML: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Lint Golang
        uses: golangci/golangci-lint-action@v6
        with:
          only-new-issues: ${{ github.event_name == 'pull_request' }}
          args: >
            --config=./.github/linters/.golangci.yml

  codespell:
    name: Check spelling
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
        with:
          exclude_file: go.mod,go.sum,assets/dist/script.js
